/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.study.modernjava;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        WhyJava8 classUnderTest = new WhyJava8();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
